### ISSUE TITLE
No module named mido

### ISSUE THREAD

**Issue by Comodore125** [Cynerd/turris-light-organ#1]
I already tried many times. but still even setting PYTHONPATH to /usr/lib was far from being helpful. 

Modules are alredy installed. 

PYTHONPATH had helped once, but now it is not working at all. Quite strange.

**Comment by Cynerd** [comment]
That seems to be very weird.

Can you check that you have files in `/usr/lib/python3.5/site-packages/mido`, specially file `__init__.py`. I expect that you do. But lets check anyway. Also probably just start python3 and try `import mido`. Also expecting no change.

So, can you post what `sys.path` contains? It should be something like this:
```
# python3
>>> import sys
>>> sys.path 
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-linux', '/usr/lib/python3.5/lib-dynload', '/usr/lib/python3.5/site-packages']
```
Specially `/usr/lib/python3.5/site-packages` is important for modules installed using pip.

**Comment by Comodore125** [comment]
`init.py` is present there. 

`import mido `in python3 seems to work. 

`sys.path `looks OK

![sys path](https://cloud.githubusercontent.com/assets/6156234/21573865/1afe662a-ceea-11e6-8f54-cb5bc9e87609.JPG)

**Comment by Comodore125** [comment]
the shit is likely to work now. strange. 

I changed nothing. very strange behaviour. 

I am hunderds of km's from my turris so I am not going to insert file but import mido is not giving me error.

**Comment by Comodore125** [comment]
DO not close, I will try it again later!

**Comment by Cynerd** [comment]
So how it is?
